# source  latest
# dest    stable-1
# result  docker/buildkit-syft-scanner:latest > docker/buildkit-syft-scanner:stable-1
#
# source  v1.0.0
# dest    stable-1
# result  docker/buildkit-syft-scanner:v1.0.0 > docker/buildkit-syft-scanner:stable-1
name: buildkit-image

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      source-tag:
        description: 'Source tag'
        required: true
        default: 'latest'
      dest-tag:
        description: 'Dest tag'
        required: true
        default: 'stable-1'
      push:
        description: 'Push the created manifest list to the registry'
        required: false
        type: boolean

env:
  DOCKERHUB_SLUG: docker/buildkit-syft-scanner

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        if: ${{ inputs.push }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      -
        name: Create
        env:
          DRYRUN_FLAG: ${{ inputs.push == 'false' && '--dry-run' || '' }}
          DEST_TAG: ${{ inputs.dest-tag }}
          SOURCE_TAG: ${{ inputs.source-tag }}
        run: |
          set -x
          docker buildx imagetools create ${DRYRUN_FLAG} --tag \
            "${{ env.DOCKERHUB_SLUG }}:${DEST_TAG}" \
            "${{ env.DOCKERHUB_SLUG }}:${SOURCE_TAG}"
